// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcnuhyequihshkhwaodf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjbnVoeWVxdWloc2hraHdhb2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTg5MzUsImV4cCI6MjA2MzkzNDkzNX0.P2JGRVtaAunKRKnP5n-_poeFu8dBX-WGeiLQ4KJzRk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);